//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/shopspring/decimal"
	"time"
)

type Anak struct {
	IDPasien           int32 `sql:"primary_key"`
	IDIbuHamil         *int32
	IDWali             int32
	NamaAnak           string
	BeratLahir         decimal.Decimal
	PanjangLahir       decimal.Decimal
	HubunganDenganWali HubunganDenganWali
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
