//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Artikel struct {
	IDArtikel      int32 `sql:"primary_key"`
	Judul          string
	IsiArtikel     string
	Kategori       *string
	StatusArtikel  StatusArtikel
	IDPenulis      int32
	IDVerifikator  *int32
	TanggalPublish *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
