//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type AuditLog struct {
	IDLog          int32 `sql:"primary_key"`
	TipeAktor      *TipeAktor
	IDUser         *int32
	IDUserSession  *uuid.UUID
	TipeAktivitas  *TipeAktivitas
	Berhasil       *bool
	Endpoint       *string
	TableName      *string
	RecordID       *string
	OldValue       *string
	NewValue       *string
	Detail         *string
	IPAddress      *string
	UserAgent      *string
	WaktuAktivitas time.Time
}
