//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Bidan struct {
	IDUser       int32 `sql:"primary_key"`
	NoStr        string
	WilayahKerja int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IsDeleted    bool
}
