//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/shopspring/decimal"
	"time"
)

type HasilPemeriksaan struct {
	IDHasilPemeriksaan int32 `sql:"primary_key"`
	IDPetugasInput     int32
	IDJadwalImunisasi  int32
	BeratBadan         decimal.Decimal
	TinggiBadan        decimal.Decimal
	LingkarKepala      decimal.Decimal
	TekananDarah       string
	StatusStunting     StatusStunting
	StatusGizi         StatusGizi
	Catatan            *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
