//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type HubunganDenganWali string

const (
	HubunganDenganWali_Kandung HubunganDenganWali = "Kandung"
	HubunganDenganWali_Tiri    HubunganDenganWali = "Tiri"
	HubunganDenganWali_Angkat  HubunganDenganWali = "Angkat"
)

var HubunganDenganWaliAllValues = []HubunganDenganWali{
	HubunganDenganWali_Kandung,
	HubunganDenganWali_Tiri,
	HubunganDenganWali_Angkat,
}

func (e *HubunganDenganWali) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Kandung":
		*e = HubunganDenganWali_Kandung
	case "Tiri":
		*e = HubunganDenganWali_Tiri
	case "Angkat":
		*e = HubunganDenganWali_Angkat
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for HubunganDenganWali enum")
	}

	return nil
}

func (e HubunganDenganWali) String() string {
	return string(e)
}
