//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type IbuHamil struct {
	IDIbuHamil      int32 `sql:"primary_key"`
	IDPasien        int32
	HamilKe         int32
	BulanMulaiHamil time.Time
	Hpht            time.Time
	StatusKehamilan StatusKehamilan
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
