//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type JenisKelamin string

const (
	JenisKelamin_LakiLaki  JenisKelamin = "Laki-Laki"
	JenisKelamin_Perempuan JenisKelamin = "Perempuan"
)

var JenisKelaminAllValues = []JenisKelamin{
	JenisKelamin_LakiLaki,
	JenisKelamin_Perempuan,
}

func (e *JenisKelamin) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Laki-Laki":
		*e = JenisKelamin_LakiLaki
	case "Perempuan":
		*e = JenisKelamin_Perempuan
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for JenisKelamin enum")
	}

	return nil
}

func (e JenisKelamin) String() string {
	return string(e)
}
