//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/shopspring/decimal"
)

type KategoriPendapatan struct {
	IDPendapatan       int32 `sql:"primary_key"`
	KategoriPendapatan string
	PendapatanMin      decimal.Decimal
	PendapatanMax      decimal.Decimal
}
