//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Lokasi struct {
	IDLokasi   int32 `sql:"primary_key"`
	NamaLokasi string
	TipeLokasi TipeLokasi
	BagianDari *int32
}
