//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Notifikasi struct {
	IDNotifikasi   int32 `sql:"primary_key"`
	IDUser         int32
	Judul          string
	Pesan          *string
	TipeNotifikasi TipeNotifikasi
	StatusBaca     bool
	TanggalKirim   time.Time
	IsDeleted      bool
	DeletedAt      *time.Time
}
