//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Pasien struct {
	IDPasien   int32 `sql:"primary_key"`
	IDPosyandu int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	IsDeleted  bool
	DeletedAt  *time.Time
}
