//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Pekerjaan struct {
	IDPekerjaan   int32 `sql:"primary_key"`
	NamaPekerjaan string
	Sektor        Sektor
}
