//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Pendidikan struct {
	IDPendidikan   int32 `sql:"primary_key"`
	NamaPendidikan string
	Jenjang        string
	LamaTahun      int32
}
