//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Posyandu struct {
	IDPosyandu   int32 `sql:"primary_key"`
	NamaPosyandu string
	IDLokasi     int32
	IDBidan      int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IsDeleted    bool
	DeletedAt    *time.Time
}
