//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Sektor string

const (
	Sektor_Formal       Sektor = "Formal"
	Sektor_Informal     Sektor = "Informal"
	Sektor_Pemerintah   Sektor = "Pemerintah"
	Sektor_Kesehatan    Sektor = "Kesehatan"
	Sektor_Pendidikan   Sektor = "Pendidikan"
	Sektor_Pertanian    Sektor = "Pertanian"
	Sektor_Domestik     Sektor = "Domestik"
	Sektor_Transportasi Sektor = "Transportasi"
)

var SektorAllValues = []Sektor{
	Sektor_Formal,
	Sektor_Informal,
	Sektor_Pemerintah,
	Sektor_Kesehatan,
	Sektor_Pendidikan,
	Sektor_Pertanian,
	Sektor_Domestik,
	Sektor_Transportasi,
}

func (e *Sektor) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Formal":
		*e = Sektor_Formal
	case "Informal":
		*e = Sektor_Informal
	case "Pemerintah":
		*e = Sektor_Pemerintah
	case "Kesehatan":
		*e = Sektor_Kesehatan
	case "Pendidikan":
		*e = Sektor_Pendidikan
	case "Pertanian":
		*e = Sektor_Pertanian
	case "Domestik":
		*e = Sektor_Domestik
	case "Transportasi":
		*e = Sektor_Transportasi
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Sektor enum")
	}

	return nil
}

func (e Sektor) String() string {
	return string(e)
}
