//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type StatusRujukan string

const (
	StatusRujukan_Diajukan StatusRujukan = "Diajukan"
	StatusRujukan_Diproses StatusRujukan = "Diproses"
	StatusRujukan_Diterima StatusRujukan = "Diterima"
	StatusRujukan_Ditolak  StatusRujukan = "Ditolak"
	StatusRujukan_Selesai  StatusRujukan = "Selesai"
)

var StatusRujukanAllValues = []StatusRujukan{
	StatusRujukan_Diajukan,
	StatusRujukan_Diproses,
	StatusRujukan_Diterima,
	StatusRujukan_Ditolak,
	StatusRujukan_Selesai,
}

func (e *StatusRujukan) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Diajukan":
		*e = StatusRujukan_Diajukan
	case "Diproses":
		*e = StatusRujukan_Diproses
	case "Diterima":
		*e = StatusRujukan_Diterima
	case "Ditolak":
		*e = StatusRujukan_Ditolak
	case "Selesai":
		*e = StatusRujukan_Selesai
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for StatusRujukan enum")
	}

	return nil
}

func (e StatusRujukan) String() string {
	return string(e)
}
