//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type StatusImunisasi string

const (
	StatusImunisasi_Sudah StatusImunisasi = "Sudah"
	StatusImunisasi_Belum StatusImunisasi = "Belum"
)

var StatusImunisasiAllValues = []StatusImunisasi{
	StatusImunisasi_Sudah,
	StatusImunisasi_Belum,
}

func (e *StatusImunisasi) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Sudah":
		*e = StatusImunisasi_Sudah
	case "Belum":
		*e = StatusImunisasi_Belum
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for StatusImunisasi enum")
	}

	return nil
}

func (e StatusImunisasi) String() string {
	return string(e)
}
