//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type StatusPasien string

const (
	StatusPasien_DalamPemantauan   StatusPasien = "Dalam Pemantauan"
	StatusPasien_Membaik           StatusPasien = "Membaik"
	StatusPasien_PerluRujukan      StatusPasien = "Perlu Rujukan"
	StatusPasien_SelesaiPemantauan StatusPasien = "Selesai Pemantauan"
)

var StatusPasienAllValues = []StatusPasien{
	StatusPasien_DalamPemantauan,
	StatusPasien_Membaik,
	StatusPasien_PerluRujukan,
	StatusPasien_SelesaiPemantauan,
}

func (e *StatusPasien) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Dalam Pemantauan":
		*e = StatusPasien_DalamPemantauan
	case "Membaik":
		*e = StatusPasien_Membaik
	case "Perlu Rujukan":
		*e = StatusPasien_PerluRujukan
	case "Selesai Pemantauan":
		*e = StatusPasien_SelesaiPemantauan
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for StatusPasien enum")
	}

	return nil
}

func (e StatusPasien) String() string {
	return string(e)
}
