//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type StatusVerifikasi string

const (
	StatusVerifikasi_Pending StatusVerifikasi = "Pending"
	StatusVerifikasi_Aktif   StatusVerifikasi = "Aktif"
	StatusVerifikasi_Ditolak StatusVerifikasi = "Ditolak"
)

var StatusVerifikasiAllValues = []StatusVerifikasi{
	StatusVerifikasi_Pending,
	StatusVerifikasi_Aktif,
	StatusVerifikasi_Ditolak,
}

func (e *StatusVerifikasi) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Pending":
		*e = StatusVerifikasi_Pending
	case "Aktif":
		*e = StatusVerifikasi_Aktif
	case "Ditolak":
		*e = StatusVerifikasi_Ditolak
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for StatusVerifikasi enum")
	}

	return nil
}

func (e StatusVerifikasi) String() string {
	return string(e)
}
