//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type StatusKehamilan string

const (
	StatusKehamilan_Trimester1 StatusKehamilan = "Trimester 1"
	StatusKehamilan_Trimester2 StatusKehamilan = "Trimester 2"
	StatusKehamilan_Trimester3 StatusKehamilan = "Trimester 3"
	StatusKehamilan_Melahirkan StatusKehamilan = "Melahirkan"
	StatusKehamilan_Nifas      StatusKehamilan = "Nifas"
	StatusKehamilan_Keguguran  StatusKehamilan = "Keguguran"
)

var StatusKehamilanAllValues = []StatusKehamilan{
	StatusKehamilan_Trimester1,
	StatusKehamilan_Trimester2,
	StatusKehamilan_Trimester3,
	StatusKehamilan_Melahirkan,
	StatusKehamilan_Nifas,
	StatusKehamilan_Keguguran,
}

func (e *StatusKehamilan) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Trimester 1":
		*e = StatusKehamilan_Trimester1
	case "Trimester 2":
		*e = StatusKehamilan_Trimester2
	case "Trimester 3":
		*e = StatusKehamilan_Trimester3
	case "Melahirkan":
		*e = StatusKehamilan_Melahirkan
	case "Nifas":
		*e = StatusKehamilan_Nifas
	case "Keguguran":
		*e = StatusKehamilan_Keguguran
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for StatusKehamilan enum")
	}

	return nil
}

func (e StatusKehamilan) String() string {
	return string(e)
}
