//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type StatusArtikel string

const (
	StatusArtikel_Draft              StatusArtikel = "Draft"
	StatusArtikel_MenungguVerifikasi StatusArtikel = "Menunggu Verifikasi"
	StatusArtikel_Dipublikasikan     StatusArtikel = "Dipublikasikan"
	StatusArtikel_Ditolak            StatusArtikel = "Ditolak"
	StatusArtikel_Diarsipkan         StatusArtikel = "Diarsipkan"
)

var StatusArtikelAllValues = []StatusArtikel{
	StatusArtikel_Draft,
	StatusArtikel_MenungguVerifikasi,
	StatusArtikel_Dipublikasikan,
	StatusArtikel_Ditolak,
	StatusArtikel_Diarsipkan,
}

func (e *StatusArtikel) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Draft":
		*e = StatusArtikel_Draft
	case "Menunggu Verifikasi":
		*e = StatusArtikel_MenungguVerifikasi
	case "Dipublikasikan":
		*e = StatusArtikel_Dipublikasikan
	case "Ditolak":
		*e = StatusArtikel_Ditolak
	case "Diarsipkan":
		*e = StatusArtikel_Diarsipkan
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for StatusArtikel enum")
	}

	return nil
}

func (e StatusArtikel) String() string {
	return string(e)
}
