//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type StatusGizi string

const (
	StatusGizi_GiziBaik        StatusGizi = "Gizi Baik"
	StatusGizi_GiziKurang      StatusGizi = "Gizi Kurang"
	StatusGizi_GiziBuruk       StatusGizi = "Gizi Buruk"
	StatusGizi_RisikoGiziLebih StatusGizi = "Risiko Gizi Lebih"
	StatusGizi_GiziLebih       StatusGizi = "Gizi Lebih"
	StatusGizi_Obesitas        StatusGizi = "Obesitas"
)

var StatusGiziAllValues = []StatusGizi{
	StatusGizi_GiziBaik,
	StatusGizi_GiziKurang,
	StatusGizi_GiziBuruk,
	StatusGizi_RisikoGiziLebih,
	StatusGizi_GiziLebih,
	StatusGizi_Obesitas,
}

func (e *StatusGizi) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Gizi Baik":
		*e = StatusGizi_GiziBaik
	case "Gizi Kurang":
		*e = StatusGizi_GiziKurang
	case "Gizi Buruk":
		*e = StatusGizi_GiziBuruk
	case "Risiko Gizi Lebih":
		*e = StatusGizi_RisikoGiziLebih
	case "Gizi Lebih":
		*e = StatusGizi_GiziLebih
	case "Obesitas":
		*e = StatusGizi_Obesitas
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for StatusGizi enum")
	}

	return nil
}

func (e StatusGizi) String() string {
	return string(e)
}
