//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type StatusStunting string

const (
	StatusStunting_Normal           StatusStunting = "Normal"
	StatusStunting_BerisikoStunting StatusStunting = "Berisiko Stunting"
	StatusStunting_Stunting         StatusStunting = "Stunting"
	StatusStunting_StuntingBerat    StatusStunting = "Stunting Berat"
)

var StatusStuntingAllValues = []StatusStunting{
	StatusStunting_Normal,
	StatusStunting_BerisikoStunting,
	StatusStunting_Stunting,
	StatusStunting_StuntingBerat,
}

func (e *StatusStunting) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Normal":
		*e = StatusStunting_Normal
	case "Berisiko Stunting":
		*e = StatusStunting_BerisikoStunting
	case "Stunting":
		*e = StatusStunting_Stunting
	case "Stunting Berat":
		*e = StatusStunting_StuntingBerat
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for StatusStunting enum")
	}

	return nil
}

func (e StatusStunting) String() string {
	return string(e)
}
