//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type StatusSession string

const (
	StatusSession_Aktif       StatusSession = "AKTIF"
	StatusSession_Kadaluwarsa StatusSession = "KADALUWARSA"
	StatusSession_Terganti    StatusSession = "TERGANTI"
	StatusSession_Dicabut     StatusSession = "DICABUT"
)

var StatusSessionAllValues = []StatusSession{
	StatusSession_Aktif,
	StatusSession_Kadaluwarsa,
	StatusSession_Terganti,
	StatusSession_Dicabut,
}

func (e *StatusSession) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "AKTIF":
		*e = StatusSession_Aktif
	case "KADALUWARSA":
		*e = StatusSession_Kadaluwarsa
	case "TERGANTI":
		*e = StatusSession_Terganti
	case "DICABUT":
		*e = StatusSession_Dicabut
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for StatusSession enum")
	}

	return nil
}

func (e StatusSession) String() string {
	return string(e)
}
