//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type TindakLanjut struct {
	IDTindakLanjut     int32 `sql:"primary_key"`
	IDHasilPemeriksaan int32
	IDBidan            int32
	CatatanMedis       *string
	Rekomendasi        *string
	JadwalKontrol      time.Time
	StatusPasien       StatusPasien
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
