//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type TipeAktivitas string

const (
	TipeAktivitas_Login                TipeAktivitas = "LOGIN"
	TipeAktivitas_Registrasi           TipeAktivitas = "REGISTRASI"
	TipeAktivitas_IPLock               TipeAktivitas = "IP_LOCK"
	TipeAktivitas_DataInsert           TipeAktivitas = "DATA_INSERT"
	TipeAktivitas_DataDelete           TipeAktivitas = "DATA_DELETE"
	TipeAktivitas_DataUpdate           TipeAktivitas = "DATA_UPDATE"
	TipeAktivitas_VerifikasiRegistrasi TipeAktivitas = "VERIFIKASI_REGISTRASI"
	TipeAktivitas_PenolakanRegistrasi  TipeAktivitas = "PENOLAKAN_REGISTRASI"
	TipeAktivitas_ForbiddenAccess      TipeAktivitas = "FORBIDDEN_ACCESS"
	TipeAktivitas_Unauthorized         TipeAktivitas = "UNAUTHORIZED"
	TipeAktivitas_BadRequest           TipeAktivitas = "BAD_REQUEST"
	TipeAktivitas_NotFound             TipeAktivitas = "NOT_FOUND"
	TipeAktivitas_Timeout              TipeAktivitas = "TIMEOUT"
	TipeAktivitas_DatabaseUnreachable  TipeAktivitas = "DATABASE_UNREACHABLE"
)

var TipeAktivitasAllValues = []TipeAktivitas{
	TipeAktivitas_Login,
	TipeAktivitas_Registrasi,
	TipeAktivitas_IPLock,
	TipeAktivitas_DataInsert,
	TipeAktivitas_DataDelete,
	TipeAktivitas_DataUpdate,
	TipeAktivitas_VerifikasiRegistrasi,
	TipeAktivitas_PenolakanRegistrasi,
	TipeAktivitas_ForbiddenAccess,
	TipeAktivitas_Unauthorized,
	TipeAktivitas_BadRequest,
	TipeAktivitas_NotFound,
	TipeAktivitas_Timeout,
	TipeAktivitas_DatabaseUnreachable,
}

func (e *TipeAktivitas) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "LOGIN":
		*e = TipeAktivitas_Login
	case "REGISTRASI":
		*e = TipeAktivitas_Registrasi
	case "IP_LOCK":
		*e = TipeAktivitas_IPLock
	case "DATA_INSERT":
		*e = TipeAktivitas_DataInsert
	case "DATA_DELETE":
		*e = TipeAktivitas_DataDelete
	case "DATA_UPDATE":
		*e = TipeAktivitas_DataUpdate
	case "VERIFIKASI_REGISTRASI":
		*e = TipeAktivitas_VerifikasiRegistrasi
	case "PENOLAKAN_REGISTRASI":
		*e = TipeAktivitas_PenolakanRegistrasi
	case "FORBIDDEN_ACCESS":
		*e = TipeAktivitas_ForbiddenAccess
	case "UNAUTHORIZED":
		*e = TipeAktivitas_Unauthorized
	case "BAD_REQUEST":
		*e = TipeAktivitas_BadRequest
	case "NOT_FOUND":
		*e = TipeAktivitas_NotFound
	case "TIMEOUT":
		*e = TipeAktivitas_Timeout
	case "DATABASE_UNREACHABLE":
		*e = TipeAktivitas_DatabaseUnreachable
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for TipeAktivitas enum")
	}

	return nil
}

func (e TipeAktivitas) String() string {
	return string(e)
}
