//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type TipeLokasi string

const (
	TipeLokasi_Provinsi  TipeLokasi = "Provinsi"
	TipeLokasi_Kabupaten TipeLokasi = "Kabupaten"
	TipeLokasi_Kota      TipeLokasi = "Kota"
	TipeLokasi_Kecamatan TipeLokasi = "Kecamatan"
	TipeLokasi_Kelurahan TipeLokasi = "Kelurahan"
)

var TipeLokasiAllValues = []TipeLokasi{
	TipeLokasi_Provinsi,
	TipeLokasi_Kabupaten,
	TipeLokasi_Kota,
	TipeLokasi_Kecamatan,
	TipeLokasi_Kelurahan,
}

func (e *TipeLokasi) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Provinsi":
		*e = TipeLokasi_Provinsi
	case "Kabupaten":
		*e = TipeLokasi_Kabupaten
	case "Kota":
		*e = TipeLokasi_Kota
	case "Kecamatan":
		*e = TipeLokasi_Kecamatan
	case "Kelurahan":
		*e = TipeLokasi_Kelurahan
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for TipeLokasi enum")
	}

	return nil
}

func (e TipeLokasi) String() string {
	return string(e)
}
