//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type TipeNotifikasi string

const (
	TipeNotifikasi_Pemeriksaan TipeNotifikasi = "Pemeriksaan"
	TipeNotifikasi_Imunisasi   TipeNotifikasi = "Imunisasi"
	TipeNotifikasi_Rujukan     TipeNotifikasi = "Rujukan"
	TipeNotifikasi_Edukasi     TipeNotifikasi = "Edukasi"
	TipeNotifikasi_Pengingat   TipeNotifikasi = "Pengingat"
)

var TipeNotifikasiAllValues = []TipeNotifikasi{
	TipeNotifikasi_Pemeriksaan,
	TipeNotifikasi_Imunisasi,
	TipeNotifikasi_Rujukan,
	TipeNotifikasi_Edukasi,
	TipeNotifikasi_Pengingat,
}

func (e *TipeNotifikasi) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Pemeriksaan":
		*e = TipeNotifikasi_Pemeriksaan
	case "Imunisasi":
		*e = TipeNotifikasi_Imunisasi
	case "Rujukan":
		*e = TipeNotifikasi_Rujukan
	case "Edukasi":
		*e = TipeNotifikasi_Edukasi
	case "Pengingat":
		*e = TipeNotifikasi_Pengingat
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for TipeNotifikasi enum")
	}

	return nil
}

func (e TipeNotifikasi) String() string {
	return string(e)
}
