//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type TipeFaskes string

const (
	TipeFaskes_FaskesTingkatPertama         TipeFaskes = "Faskes Tingkat Pertama"
	TipeFaskes_FaskesRujukanTingkatLanjutan TipeFaskes = "Faskes Rujukan Tingkat Lanjutan"
	TipeFaskes_FaskesPenunjang              TipeFaskes = "Faskes Penunjang"
)

var TipeFaskesAllValues = []TipeFaskes{
	TipeFaskes_FaskesTingkatPertama,
	TipeFaskes_FaskesRujukanTingkatLanjutan,
	TipeFaskes_FaskesPenunjang,
}

func (e *TipeFaskes) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Faskes Tingkat Pertama":
		*e = TipeFaskes_FaskesTingkatPertama
	case "Faskes Rujukan Tingkat Lanjutan":
		*e = TipeFaskes_FaskesRujukanTingkatLanjutan
	case "Faskes Penunjang":
		*e = TipeFaskes_FaskesPenunjang
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for TipeFaskes enum")
	}

	return nil
}

func (e TipeFaskes) String() string {
	return string(e)
}
