//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type TipeAktor string

const (
	TipeAktor_User      TipeAktor = "USER"
	TipeAktor_Anonymous TipeAktor = "ANONYMOUS"
	TipeAktor_System    TipeAktor = "SYSTEM"
)

var TipeAktorAllValues = []TipeAktor{
	TipeAktor_User,
	TipeAktor_Anonymous,
	TipeAktor_System,
}

func (e *TipeAktor) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "USER":
		*e = TipeAktor_User
	case "ANONYMOUS":
		*e = TipeAktor_Anonymous
	case "SYSTEM":
		*e = TipeAktor_System
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for TipeAktor enum")
	}

	return nil
}

func (e TipeAktor) String() string {
	return string(e)
}
