//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"

	"github.com/gofrs/uuid/v5"
)

type UserSession struct {
	IDSession     uuid.UUID `sql:"primary_key"`
	IDUser        int32
	StatusSession StatusSession
	IPAddress     *string
	ExpiredAt     time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
