//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserSession struct {
	IDSession     uuid.UUID `sql:"primary_key"`
	IDUser        int32
	StatusSession StatusSession
	IPAddress     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ExpiredAt     time.Time
}
