//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type UserAccount struct {
	IDUser           int32 `sql:"primary_key"`
	Email            string
	Password         string
	NoHp             string
	StatusVerifikasi StatusVerifikasi
	Nama             string
	Nik              string
	JenisKelamin     JenisKelamin
	TanggalLahir     time.Time
	IDLokasi         int32
	IDPendidikan     *int32
	IDPekerjaan      *int32
	IDPendapatan     *int32
	JumlahTanggungan *int32
	AkunKe           int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	IsDeleted        bool
	DeletedAt        *time.Time
}
