# Base
FROM docker.io/oven/bun:1.3 AS base
WORKDIR /app
COPY package*.json bun.lock ./

# Development
FROM base AS development
RUN bun install
COPY . .
CMD ["bun", "dev", "--host"]

# Build (Intermediate)
FROM base AS build-step
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
RUN bun install --frozen-lockfile
COPY . .
RUN bun run build

# STAGE 4: Production
FROM base AS production
ENV NODE_ENV=production
COPY --from=build-step /app/dist ./dist
COPY --from=build-step /app/node_modules ./node_modules
CMD ["bun", "run", "preview", "--host"]
