services:
  hop-env:
    image: docker.io/alpine:3.23.4
    env_file:
      - .env
    volumes:
      - ./etl:/files/projects/imunisasi:z
    command: sh -c "/files/projects/imunisasi/init-env.sh" && sh
    profiles: ["hop", "data_management", "dev"]

  hop:
    image: docker.io/apache/hop-web:2.17.0
    depends_on:
      hop-env:
        condition: service_completed_successfully
    ports:
      - ${HOST_IP:-127.0.0.1}:${HOP_HOST_PORT:-8090}:8080
    environment:
      HOP_PROJECT_NAME: imunisasi
      HOP_PROJECT_FOLDER: /files/projects/imunisasi
      HOP_ENVIRONMENT_NAME: "env"
      HOP_ENVIRONMENT_CONFIG_FILE_NAME_PATHS: "/files/projects/imunisasi/.env.json"
      HOP_CUSTOM_ENTRYPOINT_EXTENSION_SHELL_FILE_PATH: "/files/projects/imunisasi/init-env.sh"
    env_file:
      - .env
    volumes:
      - ./etl:/files/projects/imunisasi:z
    profiles: ["hop", "data_management", "dev"]

  warehouse:
    image: docker.io/postgres:18.3-alpine3.23
    restart: unless-stopped
    volumes:
      - ./storage/warehouse:/var/lib/postgresql
      - ./migrations:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${WAREHOUSE_DB:-imunisasi}
      POSTGRES_USER: ${WAREHOUSE_USER:-postgres}
      POSTGRES_PASSWORD: ${WAREHOUSE_PASSWORD:-postgres}
    ports:
      - ${HOST_IP:-127.0.0.1}:${WAREHOUSE_HOST_PORT:-5433}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 10
      timeout: 5s
    profiles: ["warehouse", "data_management", "dev"]

  master:
    image: docker.io/postgres:18.3-alpine3.23
    restart: unless-stopped
    volumes:
      - ./storage/master:/var/lib/postgresql
      - ./migrations:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${MASTER_DB:-imunisasi}
      POSTGRES_USER: ${MASTER_USER:-postgres}
      POSTGRES_PASSWORD: ${MASTER_PASSWORD:-postgres}
    ports:
      - ${HOST_IP:-127.0.0.1}:${MASTER_HOST_PORT:-5432}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 10
      timeout: 5s
    profiles: ["master", "information_system", "data_management", "dev"]

  staging:
    image: mcr.microsoft.com/mssql/server:2025-CU3-ubuntu-22.04
    restart: unless-stopped
    volumes:
      - ./storage/staging:/var/opt/mssql:z
      - ./migrations/data:/data:z
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${STAGING_SA_PASSWORD:-DefaultPassword123!}
      MSSQL_DB: ${STAGING_DB:-imunisasi}
    env_file:
      - .env
    ports:
      - ${HOST_PORT:-127.0.0.1}:${STAGING_HOST_PORT:-1433}:1433
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P
        ${STAGING_SA_PASSWORD:-DefaultPassword123!} -C -Q "SELECT 1" || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    profiles: ["staging", "data_management", "dev"]

  migration-warehouse:
    build:
      context: ./migrations
      dockerfile: Containerfile
    develop:
      watch:
        - action: rebuild
          path: /app/Containerfile
    volumes:
      - ./migrations:/app:z
      - go_cache:/go/pkg/mod:z
    working_dir: /app
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://${WAREHOUSE_USER:-postgres}:${WAREHOUSE_PASSWORD:-postgres}@${WAREHOUSE_HOST:-warehouse}:${WAREHOUSE_PORT:-5432}/${WAREHOUSE_DB:-imunisasi}
      GOOSE_MIGRATION_DIR: /app/warehouse
    env_file:
      - .env
    depends_on:
      warehouse:
        condition: service_healthy
    command: sh -c "goose up && sleep infinity"
    profiles: ["migration", "warehouse", "data_management", "dev"]

  migration-master:
    build:
      context: ./migrations
      dockerfile: Containerfile
    develop:
      watch:
        - action: rebuild
          path: /app/Containerfile
    volumes:
      - ./migrations:/app:z
      - go_cache:/go/pkg/mod:z
    working_dir: /app
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://${MASTER_USER:-postgres}:${MASTER_PASSWORD:-postgres}@${MASTER_HOST:-master}:${MASTER_PORT:-5432}/${MASTER_DB:-imunisasi}
      GOOSE_MIGRATION_DIR: /app/master
    env_file:
      - .env
    depends_on:
      master:
        condition: service_healthy
    command: sh -c "goose up && sleep infinity"
    profiles: ["migration", "information_system", "data_management", "master", "dev"]

  migration-staging:
    build:
      context: ./migrations
      dockerfile: Containerfile
    develop:
      watch:
        - action: rebuild
          path: /app/Containerfile
    volumes:
      - ./migrations:/app:z
      - go_cache:/go/pkg/mod:z
    working_dir: /app
    environment:
      GOOSE_DRIVER: mssql
      GOOSE_DBSTRING: sqlserver://${STAGING_USER:-sa}:${STAGING_SA_PASSWORD:-DefaultPassword123!}@staging:1433?database=${STAGING_DB:-imunisasi}
      GOOSE_MIGRATION_DIR: /app/staging
    env_file:
      - .env
    depends_on:
      staging:
        condition: service_healthy
    command: sh -c "goose up && sleep infinity"
    profiles: ["migration", "staging", "data_management", "dev"]

  webserver:
    image: docker.io/caddy:2.11.3
    restart: unless-stopped
    ports:
      - ${HOST_IP:-127.0.0.1}:${WEBSERVER_HTTP_HOST_PORT:-8080}:80
      - ${HOST_IP:-127.0.0.1}:${WEBSERVER_HTTPS_HOST_PORT:-8443}:443
      - ${HOST_IP:-127.0.0.1}:${WEBSERVER_HTTPS_HOST_PORT:-8443}:443/udp
      - ${HOST_IP:-127.0.0.1}:${WEBSERVER_ADMIN_HOST_PORT:-2019}:2019
    env_file:
      - .env
    volumes:
      - ./webserver:/etc/caddy
    profiles: ["webserver", "information_system", "dev"]

  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    develop:
      watch:
        - action: rebuild
          path: /app/go.mod
        - action: rebuild
          path: /app/Containerfile
    volumes:
      - ./backend:/app:z
      - go_cache:/go/pkg/mod:z
    working_dir: /app
    ports:
      - 8070:8080
    env_file:
      - .env
    command: sh -c "go mod tidy && air -c .air.toml"
    profiles: ["backend", "information_system", "dev"]

  frontend:
    build:
      context: ./frontend
      target: development
      dockerfile: Containerfile
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: /app/package.json
    volumes:
      - ./frontend:/app:z
      - node_cache:/app/node_modules
    env_file: .env
    environment:
      - NODE_ENV=development
    profiles: ["frontend", "information_system", "dev"]

volumes:
  go_cache:
  node_cache:
