FROM docker.io/library/golang:1.26.2-alpine3.23 as base

WORKDIR /app
COPY go.* /app/
RUN go mod download

FROM base AS development
RUN go install github.com/go-jet/jet/v2/cmd/jet@latest
RUN go install github.com/air-verse/air@latest
CMD ["air","-c",".air.toml"]

FROM base AS integration_test
CMD go test -p 1 -v -tags=integration ./...

FROM base AS production
CMD go run cmd/api/main.go
