//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var HubunganDenganWali = &struct {
	Kandung postgres.StringExpression
	Tiri    postgres.StringExpression
	Angkat  postgres.StringExpression
}{
	Kandung: postgres.NewEnumValue("Kandung"),
	Tiri:    postgres.NewEnumValue("Tiri"),
	Angkat:  postgres.NewEnumValue("Angkat"),
}
