//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var Sektor = &struct {
	Formal       postgres.StringExpression
	Informal     postgres.StringExpression
	Pemerintah   postgres.StringExpression
	Kesehatan    postgres.StringExpression
	Pendidikan   postgres.StringExpression
	Pertanian    postgres.StringExpression
	Domestik     postgres.StringExpression
	Transportasi postgres.StringExpression
}{
	Formal:       postgres.NewEnumValue("Formal"),
	Informal:     postgres.NewEnumValue("Informal"),
	Pemerintah:   postgres.NewEnumValue("Pemerintah"),
	Kesehatan:    postgres.NewEnumValue("Kesehatan"),
	Pendidikan:   postgres.NewEnumValue("Pendidikan"),
	Pertanian:    postgres.NewEnumValue("Pertanian"),
	Domestik:     postgres.NewEnumValue("Domestik"),
	Transportasi: postgres.NewEnumValue("Transportasi"),
}
