//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var StatusPasien = &struct {
	DalamPemantauan   postgres.StringExpression
	Membaik           postgres.StringExpression
	PerluRujukan      postgres.StringExpression
	SelesaiPemantauan postgres.StringExpression
}{
	DalamPemantauan:   postgres.NewEnumValue("Dalam Pemantauan"),
	Membaik:           postgres.NewEnumValue("Membaik"),
	PerluRujukan:      postgres.NewEnumValue("Perlu Rujukan"),
	SelesaiPemantauan: postgres.NewEnumValue("Selesai Pemantauan"),
}
