//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var StatusStunting = &struct {
	Normal           postgres.StringExpression
	BerisikoStunting postgres.StringExpression
	Stunting         postgres.StringExpression
	StuntingBerat    postgres.StringExpression
}{
	Normal:           postgres.NewEnumValue("Normal"),
	BerisikoStunting: postgres.NewEnumValue("Berisiko Stunting"),
	Stunting:         postgres.NewEnumValue("Stunting"),
	StuntingBerat:    postgres.NewEnumValue("Stunting Berat"),
}
