//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var StatusSession = &struct {
	Aktif       postgres.StringExpression
	Kadaluwarsa postgres.StringExpression
	Terganti    postgres.StringExpression
	Dicabut     postgres.StringExpression
}{
	Aktif:       postgres.NewEnumValue("AKTIF"),
	Kadaluwarsa: postgres.NewEnumValue("KADALUWARSA"),
	Terganti:    postgres.NewEnumValue("TERGANTI"),
	Dicabut:     postgres.NewEnumValue("DICABUT"),
}
