//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var StatusArtikel = &struct {
	Draft              postgres.StringExpression
	MenungguVerifikasi postgres.StringExpression
	Dipublikasikan     postgres.StringExpression
	Ditolak            postgres.StringExpression
	Diarsipkan         postgres.StringExpression
}{
	Draft:              postgres.NewEnumValue("Draft"),
	MenungguVerifikasi: postgres.NewEnumValue("Menunggu Verifikasi"),
	Dipublikasikan:     postgres.NewEnumValue("Dipublikasikan"),
	Ditolak:            postgres.NewEnumValue("Ditolak"),
	Diarsipkan:         postgres.NewEnumValue("Diarsipkan"),
}
