//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var StatusGizi = &struct {
	GiziBaik        postgres.StringExpression
	GiziKurang      postgres.StringExpression
	GiziBuruk       postgres.StringExpression
	RisikoGiziLebih postgres.StringExpression
	GiziLebih       postgres.StringExpression
	Obesitas        postgres.StringExpression
}{
	GiziBaik:        postgres.NewEnumValue("Gizi Baik"),
	GiziKurang:      postgres.NewEnumValue("Gizi Kurang"),
	GiziBuruk:       postgres.NewEnumValue("Gizi Buruk"),
	RisikoGiziLebih: postgres.NewEnumValue("Risiko Gizi Lebih"),
	GiziLebih:       postgres.NewEnumValue("Gizi Lebih"),
	Obesitas:        postgres.NewEnumValue("Obesitas"),
}
