//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var StatusRujukan = &struct {
	Diajukan postgres.StringExpression
	Diproses postgres.StringExpression
	Diterima postgres.StringExpression
	Ditolak  postgres.StringExpression
	Selesai  postgres.StringExpression
}{
	Diajukan: postgres.NewEnumValue("Diajukan"),
	Diproses: postgres.NewEnumValue("Diproses"),
	Diterima: postgres.NewEnumValue("Diterima"),
	Ditolak:  postgres.NewEnumValue("Ditolak"),
	Selesai:  postgres.NewEnumValue("Selesai"),
}
