//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var StatusKehamilan = &struct {
	Trimester1 postgres.StringExpression
	Trimester2 postgres.StringExpression
	Trimester3 postgres.StringExpression
	Melahirkan postgres.StringExpression
	Nifas      postgres.StringExpression
	Keguguran  postgres.StringExpression
}{
	Trimester1: postgres.NewEnumValue("Trimester 1"),
	Trimester2: postgres.NewEnumValue("Trimester 2"),
	Trimester3: postgres.NewEnumValue("Trimester 3"),
	Melahirkan: postgres.NewEnumValue("Melahirkan"),
	Nifas:      postgres.NewEnumValue("Nifas"),
	Keguguran:  postgres.NewEnumValue("Keguguran"),
}
