//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var StatusVerifikasi = &struct {
	Pending postgres.StringExpression
	Aktif   postgres.StringExpression
	Ditolak postgres.StringExpression
}{
	Pending: postgres.NewEnumValue("Pending"),
	Aktif:   postgres.NewEnumValue("Aktif"),
	Ditolak: postgres.NewEnumValue("Ditolak"),
}
