//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var TipeAktivitas = &struct {
	Login                postgres.StringExpression
	Registrasi           postgres.StringExpression
	IPLock               postgres.StringExpression
	DataInsert           postgres.StringExpression
	DataDelete           postgres.StringExpression
	DataUpdate           postgres.StringExpression
	VerifikasiRegistrasi postgres.StringExpression
	PenolakanRegistrasi  postgres.StringExpression
	ForbiddenAccess      postgres.StringExpression
	Unauthorized         postgres.StringExpression
	BadRequest           postgres.StringExpression
	NotFound             postgres.StringExpression
	Timeout              postgres.StringExpression
	DatabaseUnreachable  postgres.StringExpression
}{
	Login:                postgres.NewEnumValue("LOGIN"),
	Registrasi:           postgres.NewEnumValue("REGISTRASI"),
	IPLock:               postgres.NewEnumValue("IP_LOCK"),
	DataInsert:           postgres.NewEnumValue("DATA_INSERT"),
	DataDelete:           postgres.NewEnumValue("DATA_DELETE"),
	DataUpdate:           postgres.NewEnumValue("DATA_UPDATE"),
	VerifikasiRegistrasi: postgres.NewEnumValue("VERIFIKASI_REGISTRASI"),
	PenolakanRegistrasi:  postgres.NewEnumValue("PENOLAKAN_REGISTRASI"),
	ForbiddenAccess:      postgres.NewEnumValue("FORBIDDEN_ACCESS"),
	Unauthorized:         postgres.NewEnumValue("UNAUTHORIZED"),
	BadRequest:           postgres.NewEnumValue("BAD_REQUEST"),
	NotFound:             postgres.NewEnumValue("NOT_FOUND"),
	Timeout:              postgres.NewEnumValue("TIMEOUT"),
	DatabaseUnreachable:  postgres.NewEnumValue("DATABASE_UNREACHABLE"),
}
