//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var TipeNotifikasi = &struct {
	Pemeriksaan postgres.StringExpression
	Imunisasi   postgres.StringExpression
	Rujukan     postgres.StringExpression
	Edukasi     postgres.StringExpression
	Pengingat   postgres.StringExpression
}{
	Pemeriksaan: postgres.NewEnumValue("Pemeriksaan"),
	Imunisasi:   postgres.NewEnumValue("Imunisasi"),
	Rujukan:     postgres.NewEnumValue("Rujukan"),
	Edukasi:     postgres.NewEnumValue("Edukasi"),
	Pengingat:   postgres.NewEnumValue("Pengingat"),
}
