//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var TipeAktor = &struct {
	User      postgres.StringExpression
	Anonymous postgres.StringExpression
	System    postgres.StringExpression
}{
	User:      postgres.NewEnumValue("USER"),
	Anonymous: postgres.NewEnumValue("ANONYMOUS"),
	System:    postgres.NewEnumValue("SYSTEM"),
}
