//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var TipeFaskes = &struct {
	FaskesTingkatPertama         postgres.StringExpression
	FaskesRujukanTingkatLanjutan postgres.StringExpression
	FaskesPenunjang              postgres.StringExpression
}{
	FaskesTingkatPertama:         postgres.NewEnumValue("Faskes Tingkat Pertama"),
	FaskesRujukanTingkatLanjutan: postgres.NewEnumValue("Faskes Rujukan Tingkat Lanjutan"),
	FaskesPenunjang:              postgres.NewEnumValue("Faskes Penunjang"),
}
