//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var TipeLokasi = &struct {
	Provinsi  postgres.StringExpression
	Kabupaten postgres.StringExpression
	Kota      postgres.StringExpression
	Kecamatan postgres.StringExpression
	Kelurahan postgres.StringExpression
}{
	Provinsi:  postgres.NewEnumValue("Provinsi"),
	Kabupaten: postgres.NewEnumValue("Kabupaten"),
	Kota:      postgres.NewEnumValue("Kota"),
	Kecamatan: postgres.NewEnumValue("Kecamatan"),
	Kelurahan: postgres.NewEnumValue("Kelurahan"),
}
