//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Anak = newAnakTable("public", "anak", "")

type anakTable struct {
	postgres.Table

	// Columns
	IDPasien           postgres.ColumnInteger
	IDIbuHamil         postgres.ColumnInteger
	IDWali             postgres.ColumnInteger
	NamaAnak           postgres.ColumnString
	BeratLahir         postgres.ColumnFloat
	PanjangLahir       postgres.ColumnFloat
	HubunganDenganWali postgres.ColumnString
	CreatedAt          postgres.ColumnTimestampz
	UpdatedAt          postgres.ColumnTimestampz
	IsDeleted          postgres.ColumnBool

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AnakTable struct {
	anakTable

	EXCLUDED anakTable
}

// AS creates new AnakTable with assigned alias
func (a AnakTable) AS(alias string) *AnakTable {
	return newAnakTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AnakTable with assigned schema name
func (a AnakTable) FromSchema(schemaName string) *AnakTable {
	return newAnakTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AnakTable with assigned table prefix
func (a AnakTable) WithPrefix(prefix string) *AnakTable {
	return newAnakTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AnakTable with assigned table suffix
func (a AnakTable) WithSuffix(suffix string) *AnakTable {
	return newAnakTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAnakTable(schemaName, tableName, alias string) *AnakTable {
	return &AnakTable{
		anakTable: newAnakTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newAnakTableImpl("", "excluded", ""),
	}
}

func newAnakTableImpl(schemaName, tableName, alias string) anakTable {
	var (
		IDPasienColumn           = postgres.IntegerColumn("id_pasien")
		IDIbuHamilColumn         = postgres.IntegerColumn("id_ibu_hamil")
		IDWaliColumn             = postgres.IntegerColumn("id_wali")
		NamaAnakColumn           = postgres.StringColumn("nama_anak")
		BeratLahirColumn         = postgres.FloatColumn("berat_lahir")
		PanjangLahirColumn       = postgres.FloatColumn("panjang_lahir")
		HubunganDenganWaliColumn = postgres.StringColumn("hubungan_dengan_wali")
		CreatedAtColumn          = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn          = postgres.TimestampzColumn("updated_at")
		IsDeletedColumn          = postgres.BoolColumn("is_deleted")
		allColumns               = postgres.ColumnList{IDPasienColumn, IDIbuHamilColumn, IDWaliColumn, NamaAnakColumn, BeratLahirColumn, PanjangLahirColumn, HubunganDenganWaliColumn, CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
		mutableColumns           = postgres.ColumnList{IDIbuHamilColumn, IDWaliColumn, NamaAnakColumn, BeratLahirColumn, PanjangLahirColumn, HubunganDenganWaliColumn, CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
		defaultColumns           = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
	)

	return anakTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDPasien:           IDPasienColumn,
		IDIbuHamil:         IDIbuHamilColumn,
		IDWali:             IDWaliColumn,
		NamaAnak:           NamaAnakColumn,
		BeratLahir:         BeratLahirColumn,
		PanjangLahir:       PanjangLahirColumn,
		HubunganDenganWali: HubunganDenganWaliColumn,
		CreatedAt:          CreatedAtColumn,
		UpdatedAt:          UpdatedAtColumn,
		IsDeleted:          IsDeletedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
