//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Artikel = newArtikelTable("public", "artikel", "")

type artikelTable struct {
	postgres.Table

	// Columns
	IDArtikel      postgres.ColumnInteger
	Judul          postgres.ColumnString
	IsiArtikel     postgres.ColumnString
	Kategori       postgres.ColumnString
	StatusArtikel  postgres.ColumnString
	IDPenulis      postgres.ColumnInteger
	IDVerifikator  postgres.ColumnInteger
	TanggalPublish postgres.ColumnDate
	CreatedAt      postgres.ColumnTimestampz
	UpdatedAt      postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ArtikelTable struct {
	artikelTable

	EXCLUDED artikelTable
}

// AS creates new ArtikelTable with assigned alias
func (a ArtikelTable) AS(alias string) *ArtikelTable {
	return newArtikelTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ArtikelTable with assigned schema name
func (a ArtikelTable) FromSchema(schemaName string) *ArtikelTable {
	return newArtikelTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ArtikelTable with assigned table prefix
func (a ArtikelTable) WithPrefix(prefix string) *ArtikelTable {
	return newArtikelTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ArtikelTable with assigned table suffix
func (a ArtikelTable) WithSuffix(suffix string) *ArtikelTable {
	return newArtikelTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newArtikelTable(schemaName, tableName, alias string) *ArtikelTable {
	return &ArtikelTable{
		artikelTable: newArtikelTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newArtikelTableImpl("", "excluded", ""),
	}
}

func newArtikelTableImpl(schemaName, tableName, alias string) artikelTable {
	var (
		IDArtikelColumn      = postgres.IntegerColumn("id_artikel")
		JudulColumn          = postgres.StringColumn("judul")
		IsiArtikelColumn     = postgres.StringColumn("isi_artikel")
		KategoriColumn       = postgres.StringColumn("kategori")
		StatusArtikelColumn  = postgres.StringColumn("status_artikel")
		IDPenulisColumn      = postgres.IntegerColumn("id_penulis")
		IDVerifikatorColumn  = postgres.IntegerColumn("id_verifikator")
		TanggalPublishColumn = postgres.DateColumn("tanggal_publish")
		CreatedAtColumn      = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn      = postgres.TimestampzColumn("updated_at")
		allColumns           = postgres.ColumnList{IDArtikelColumn, JudulColumn, IsiArtikelColumn, KategoriColumn, StatusArtikelColumn, IDPenulisColumn, IDVerifikatorColumn, TanggalPublishColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns       = postgres.ColumnList{JudulColumn, IsiArtikelColumn, KategoriColumn, StatusArtikelColumn, IDPenulisColumn, IDVerifikatorColumn, TanggalPublishColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns       = postgres.ColumnList{IDArtikelColumn, StatusArtikelColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return artikelTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDArtikel:      IDArtikelColumn,
		Judul:          JudulColumn,
		IsiArtikel:     IsiArtikelColumn,
		Kategori:       KategoriColumn,
		StatusArtikel:  StatusArtikelColumn,
		IDPenulis:      IDPenulisColumn,
		IDVerifikator:  IDVerifikatorColumn,
		TanggalPublish: TanggalPublishColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
