//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AuditLog = newAuditLogTable("public", "audit_log", "")

type auditLogTable struct {
	postgres.Table

	// Columns
	IDLog          postgres.ColumnInteger
	TipeAktor      postgres.ColumnString
	IDUser         postgres.ColumnInteger
	IDUserSession  postgres.ColumnString
	TipeAktivitas  postgres.ColumnString
	Berhasil       postgres.ColumnBool
	Endpoint       postgres.ColumnString
	TableName_     postgres.ColumnString
	RecordID       postgres.ColumnString
	OldValue       postgres.ColumnString
	NewValue       postgres.ColumnString
	Detail         postgres.ColumnString
	IPAddress      postgres.ColumnString
	UserAgent      postgres.ColumnString
	WaktuAktivitas postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AuditLogTable struct {
	auditLogTable

	EXCLUDED auditLogTable
}

// AS creates new AuditLogTable with assigned alias
func (a AuditLogTable) AS(alias string) *AuditLogTable {
	return newAuditLogTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AuditLogTable with assigned schema name
func (a AuditLogTable) FromSchema(schemaName string) *AuditLogTable {
	return newAuditLogTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AuditLogTable with assigned table prefix
func (a AuditLogTable) WithPrefix(prefix string) *AuditLogTable {
	return newAuditLogTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AuditLogTable with assigned table suffix
func (a AuditLogTable) WithSuffix(suffix string) *AuditLogTable {
	return newAuditLogTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAuditLogTable(schemaName, tableName, alias string) *AuditLogTable {
	return &AuditLogTable{
		auditLogTable: newAuditLogTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newAuditLogTableImpl("", "excluded", ""),
	}
}

func newAuditLogTableImpl(schemaName, tableName, alias string) auditLogTable {
	var (
		IDLogColumn          = postgres.IntegerColumn("id_log")
		TipeAktorColumn      = postgres.StringColumn("tipe_aktor")
		IDUserColumn         = postgres.IntegerColumn("id_user")
		IDUserSessionColumn  = postgres.StringColumn("id_user_session")
		TipeAktivitasColumn  = postgres.StringColumn("tipe_aktivitas")
		BerhasilColumn       = postgres.BoolColumn("berhasil")
		EndpointColumn       = postgres.StringColumn("endpoint")
		TableName_Column     = postgres.StringColumn("table_name")
		RecordIDColumn       = postgres.StringColumn("record_id")
		OldValueColumn       = postgres.StringColumn("old_value")
		NewValueColumn       = postgres.StringColumn("new_value")
		DetailColumn         = postgres.StringColumn("detail")
		IPAddressColumn      = postgres.StringColumn("ip_address")
		UserAgentColumn      = postgres.StringColumn("user_agent")
		WaktuAktivitasColumn = postgres.TimestampzColumn("waktu_aktivitas")
		allColumns           = postgres.ColumnList{IDLogColumn, TipeAktorColumn, IDUserColumn, IDUserSessionColumn, TipeAktivitasColumn, BerhasilColumn, EndpointColumn, TableName_Column, RecordIDColumn, OldValueColumn, NewValueColumn, DetailColumn, IPAddressColumn, UserAgentColumn, WaktuAktivitasColumn}
		mutableColumns       = postgres.ColumnList{TipeAktorColumn, IDUserColumn, IDUserSessionColumn, TipeAktivitasColumn, BerhasilColumn, EndpointColumn, TableName_Column, RecordIDColumn, OldValueColumn, NewValueColumn, DetailColumn, IPAddressColumn, UserAgentColumn, WaktuAktivitasColumn}
		defaultColumns       = postgres.ColumnList{IDLogColumn, WaktuAktivitasColumn}
	)

	return auditLogTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDLog:          IDLogColumn,
		TipeAktor:      TipeAktorColumn,
		IDUser:         IDUserColumn,
		IDUserSession:  IDUserSessionColumn,
		TipeAktivitas:  TipeAktivitasColumn,
		Berhasil:       BerhasilColumn,
		Endpoint:       EndpointColumn,
		TableName_:     TableName_Column,
		RecordID:       RecordIDColumn,
		OldValue:       OldValueColumn,
		NewValue:       NewValueColumn,
		Detail:         DetailColumn,
		IPAddress:      IPAddressColumn,
		UserAgent:      UserAgentColumn,
		WaktuAktivitas: WaktuAktivitasColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
