//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Bidan = newBidanTable("public", "bidan", "")

type bidanTable struct {
	postgres.Table

	// Columns
	IDUser       postgres.ColumnInteger
	NoStr        postgres.ColumnString
	WilayahKerja postgres.ColumnInteger
	CreatedAt    postgres.ColumnTimestampz
	UpdatedAt    postgres.ColumnTimestampz
	IsDeleted    postgres.ColumnBool

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type BidanTable struct {
	bidanTable

	EXCLUDED bidanTable
}

// AS creates new BidanTable with assigned alias
func (a BidanTable) AS(alias string) *BidanTable {
	return newBidanTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BidanTable with assigned schema name
func (a BidanTable) FromSchema(schemaName string) *BidanTable {
	return newBidanTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BidanTable with assigned table prefix
func (a BidanTable) WithPrefix(prefix string) *BidanTable {
	return newBidanTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BidanTable with assigned table suffix
func (a BidanTable) WithSuffix(suffix string) *BidanTable {
	return newBidanTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBidanTable(schemaName, tableName, alias string) *BidanTable {
	return &BidanTable{
		bidanTable: newBidanTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newBidanTableImpl("", "excluded", ""),
	}
}

func newBidanTableImpl(schemaName, tableName, alias string) bidanTable {
	var (
		IDUserColumn       = postgres.IntegerColumn("id_user")
		NoStrColumn        = postgres.StringColumn("no_str")
		WilayahKerjaColumn = postgres.IntegerColumn("wilayah_kerja")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampzColumn("updated_at")
		IsDeletedColumn    = postgres.BoolColumn("is_deleted")
		allColumns         = postgres.ColumnList{IDUserColumn, NoStrColumn, WilayahKerjaColumn, CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
		mutableColumns     = postgres.ColumnList{NoStrColumn, WilayahKerjaColumn, CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
		defaultColumns     = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
	)

	return bidanTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDUser:       IDUserColumn,
		NoStr:        NoStrColumn,
		WilayahKerja: WilayahKerjaColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,
		IsDeleted:    IsDeletedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
