//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var DinasKesehatan = newDinasKesehatanTable("public", "dinas_kesehatan", "")

type dinasKesehatanTable struct {
	postgres.Table

	// Columns
	IDUser    postgres.ColumnInteger
	CreatedAt postgres.ColumnTimestampz
	UpdatedAt postgres.ColumnTimestampz
	IsDeleted postgres.ColumnBool
	DeletedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type DinasKesehatanTable struct {
	dinasKesehatanTable

	EXCLUDED dinasKesehatanTable
}

// AS creates new DinasKesehatanTable with assigned alias
func (a DinasKesehatanTable) AS(alias string) *DinasKesehatanTable {
	return newDinasKesehatanTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DinasKesehatanTable with assigned schema name
func (a DinasKesehatanTable) FromSchema(schemaName string) *DinasKesehatanTable {
	return newDinasKesehatanTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DinasKesehatanTable with assigned table prefix
func (a DinasKesehatanTable) WithPrefix(prefix string) *DinasKesehatanTable {
	return newDinasKesehatanTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DinasKesehatanTable with assigned table suffix
func (a DinasKesehatanTable) WithSuffix(suffix string) *DinasKesehatanTable {
	return newDinasKesehatanTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDinasKesehatanTable(schemaName, tableName, alias string) *DinasKesehatanTable {
	return &DinasKesehatanTable{
		dinasKesehatanTable: newDinasKesehatanTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newDinasKesehatanTableImpl("", "excluded", ""),
	}
}

func newDinasKesehatanTableImpl(schemaName, tableName, alias string) dinasKesehatanTable {
	var (
		IDUserColumn    = postgres.IntegerColumn("id_user")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn = postgres.TimestampzColumn("updated_at")
		IsDeletedColumn = postgres.BoolColumn("is_deleted")
		DeletedAtColumn = postgres.TimestampzColumn("deleted_at")
		allColumns      = postgres.ColumnList{IDUserColumn, CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn, DeletedAtColumn}
		mutableColumns  = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn, DeletedAtColumn}
		defaultColumns  = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
	)

	return dinasKesehatanTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDUser:    IDUserColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,
		IsDeleted: IsDeletedColumn,
		DeletedAt: DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
