//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var FasilitasKesehatan = newFasilitasKesehatanTable("public", "fasilitas_kesehatan", "")

type fasilitasKesehatanTable struct {
	postgres.Table

	// Columns
	IDFaskes   postgres.ColumnInteger
	NamaFaskes postgres.ColumnString
	TipeFaskes postgres.ColumnString
	IDLokasi   postgres.ColumnInteger
	CreatedAt  postgres.ColumnTimestampz
	UpdatedAt  postgres.ColumnTimestampz
	IsDeleted  postgres.ColumnBool
	DeletedAt  postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type FasilitasKesehatanTable struct {
	fasilitasKesehatanTable

	EXCLUDED fasilitasKesehatanTable
}

// AS creates new FasilitasKesehatanTable with assigned alias
func (a FasilitasKesehatanTable) AS(alias string) *FasilitasKesehatanTable {
	return newFasilitasKesehatanTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FasilitasKesehatanTable with assigned schema name
func (a FasilitasKesehatanTable) FromSchema(schemaName string) *FasilitasKesehatanTable {
	return newFasilitasKesehatanTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FasilitasKesehatanTable with assigned table prefix
func (a FasilitasKesehatanTable) WithPrefix(prefix string) *FasilitasKesehatanTable {
	return newFasilitasKesehatanTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FasilitasKesehatanTable with assigned table suffix
func (a FasilitasKesehatanTable) WithSuffix(suffix string) *FasilitasKesehatanTable {
	return newFasilitasKesehatanTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFasilitasKesehatanTable(schemaName, tableName, alias string) *FasilitasKesehatanTable {
	return &FasilitasKesehatanTable{
		fasilitasKesehatanTable: newFasilitasKesehatanTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newFasilitasKesehatanTableImpl("", "excluded", ""),
	}
}

func newFasilitasKesehatanTableImpl(schemaName, tableName, alias string) fasilitasKesehatanTable {
	var (
		IDFaskesColumn   = postgres.IntegerColumn("id_faskes")
		NamaFaskesColumn = postgres.StringColumn("nama_faskes")
		TipeFaskesColumn = postgres.StringColumn("tipe_faskes")
		IDLokasiColumn   = postgres.IntegerColumn("id_lokasi")
		CreatedAtColumn  = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn  = postgres.TimestampzColumn("updated_at")
		IsDeletedColumn  = postgres.BoolColumn("is_deleted")
		DeletedAtColumn  = postgres.TimestampzColumn("deleted_at")
		allColumns       = postgres.ColumnList{IDFaskesColumn, NamaFaskesColumn, TipeFaskesColumn, IDLokasiColumn, CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn, DeletedAtColumn}
		mutableColumns   = postgres.ColumnList{NamaFaskesColumn, TipeFaskesColumn, IDLokasiColumn, CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn, DeletedAtColumn}
		defaultColumns   = postgres.ColumnList{IDFaskesColumn, CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
	)

	return fasilitasKesehatanTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDFaskes:   IDFaskesColumn,
		NamaFaskes: NamaFaskesColumn,
		TipeFaskes: TipeFaskesColumn,
		IDLokasi:   IDLokasiColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,
		IsDeleted:  IsDeletedColumn,
		DeletedAt:  DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
