//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var IbuHamil = newIbuHamilTable("public", "ibu_hamil", "")

type ibuHamilTable struct {
	postgres.Table

	// Columns
	IDIbuHamil      postgres.ColumnInteger
	IDPasien        postgres.ColumnInteger
	HamilKe         postgres.ColumnInteger
	BulanMulaiHamil postgres.ColumnDate
	Hpht            postgres.ColumnDate
	StatusKehamilan postgres.ColumnString
	CreatedAt       postgres.ColumnTimestampz
	UpdatedAt       postgres.ColumnTimestampz
	IsDeleted       postgres.ColumnBool

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type IbuHamilTable struct {
	ibuHamilTable

	EXCLUDED ibuHamilTable
}

// AS creates new IbuHamilTable with assigned alias
func (a IbuHamilTable) AS(alias string) *IbuHamilTable {
	return newIbuHamilTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new IbuHamilTable with assigned schema name
func (a IbuHamilTable) FromSchema(schemaName string) *IbuHamilTable {
	return newIbuHamilTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new IbuHamilTable with assigned table prefix
func (a IbuHamilTable) WithPrefix(prefix string) *IbuHamilTable {
	return newIbuHamilTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new IbuHamilTable with assigned table suffix
func (a IbuHamilTable) WithSuffix(suffix string) *IbuHamilTable {
	return newIbuHamilTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newIbuHamilTable(schemaName, tableName, alias string) *IbuHamilTable {
	return &IbuHamilTable{
		ibuHamilTable: newIbuHamilTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newIbuHamilTableImpl("", "excluded", ""),
	}
}

func newIbuHamilTableImpl(schemaName, tableName, alias string) ibuHamilTable {
	var (
		IDIbuHamilColumn      = postgres.IntegerColumn("id_ibu_hamil")
		IDPasienColumn        = postgres.IntegerColumn("id_pasien")
		HamilKeColumn         = postgres.IntegerColumn("hamil_ke")
		BulanMulaiHamilColumn = postgres.DateColumn("bulan_mulai_hamil")
		HphtColumn            = postgres.DateColumn("hpht")
		StatusKehamilanColumn = postgres.StringColumn("status_kehamilan")
		CreatedAtColumn       = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn       = postgres.TimestampzColumn("updated_at")
		IsDeletedColumn       = postgres.BoolColumn("is_deleted")
		allColumns            = postgres.ColumnList{IDIbuHamilColumn, IDPasienColumn, HamilKeColumn, BulanMulaiHamilColumn, HphtColumn, StatusKehamilanColumn, CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
		mutableColumns        = postgres.ColumnList{IDPasienColumn, HamilKeColumn, BulanMulaiHamilColumn, HphtColumn, StatusKehamilanColumn, CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
		defaultColumns        = postgres.ColumnList{IDIbuHamilColumn, CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
	)

	return ibuHamilTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDIbuHamil:      IDIbuHamilColumn,
		IDPasien:        IDPasienColumn,
		HamilKe:         HamilKeColumn,
		BulanMulaiHamil: BulanMulaiHamilColumn,
		Hpht:            HphtColumn,
		StatusKehamilan: StatusKehamilanColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,
		IsDeleted:       IsDeletedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
