//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var KaderPosyandu = newKaderPosyanduTable("public", "kader_posyandu", "")

type kaderPosyanduTable struct {
	postgres.Table

	// Columns
	IDUser     postgres.ColumnInteger
	NoSk       postgres.ColumnString
	IDPosyandu postgres.ColumnInteger
	CreatedAt  postgres.ColumnTimestampz
	UpdatedAt  postgres.ColumnTimestampz
	IsDeleted  postgres.ColumnBool

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type KaderPosyanduTable struct {
	kaderPosyanduTable

	EXCLUDED kaderPosyanduTable
}

// AS creates new KaderPosyanduTable with assigned alias
func (a KaderPosyanduTable) AS(alias string) *KaderPosyanduTable {
	return newKaderPosyanduTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new KaderPosyanduTable with assigned schema name
func (a KaderPosyanduTable) FromSchema(schemaName string) *KaderPosyanduTable {
	return newKaderPosyanduTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new KaderPosyanduTable with assigned table prefix
func (a KaderPosyanduTable) WithPrefix(prefix string) *KaderPosyanduTable {
	return newKaderPosyanduTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new KaderPosyanduTable with assigned table suffix
func (a KaderPosyanduTable) WithSuffix(suffix string) *KaderPosyanduTable {
	return newKaderPosyanduTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newKaderPosyanduTable(schemaName, tableName, alias string) *KaderPosyanduTable {
	return &KaderPosyanduTable{
		kaderPosyanduTable: newKaderPosyanduTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newKaderPosyanduTableImpl("", "excluded", ""),
	}
}

func newKaderPosyanduTableImpl(schemaName, tableName, alias string) kaderPosyanduTable {
	var (
		IDUserColumn     = postgres.IntegerColumn("id_user")
		NoSkColumn       = postgres.StringColumn("no_sk")
		IDPosyanduColumn = postgres.IntegerColumn("id_posyandu")
		CreatedAtColumn  = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn  = postgres.TimestampzColumn("updated_at")
		IsDeletedColumn  = postgres.BoolColumn("is_deleted")
		allColumns       = postgres.ColumnList{IDUserColumn, NoSkColumn, IDPosyanduColumn, CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
		mutableColumns   = postgres.ColumnList{NoSkColumn, IDPosyanduColumn, CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
		defaultColumns   = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
	)

	return kaderPosyanduTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDUser:     IDUserColumn,
		NoSk:       NoSkColumn,
		IDPosyandu: IDPosyanduColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,
		IsDeleted:  IsDeletedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
