//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Notifikasi = newNotifikasiTable("public", "notifikasi", "")

type notifikasiTable struct {
	postgres.Table

	// Columns
	IDNotifikasi   postgres.ColumnInteger
	IDUser         postgres.ColumnInteger
	Judul          postgres.ColumnString
	Pesan          postgres.ColumnString
	TipeNotifikasi postgres.ColumnString
	StatusBaca     postgres.ColumnBool
	TanggalKirim   postgres.ColumnTimestampz
	IsDeleted      postgres.ColumnBool
	DeletedAt      postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type NotifikasiTable struct {
	notifikasiTable

	EXCLUDED notifikasiTable
}

// AS creates new NotifikasiTable with assigned alias
func (a NotifikasiTable) AS(alias string) *NotifikasiTable {
	return newNotifikasiTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new NotifikasiTable with assigned schema name
func (a NotifikasiTable) FromSchema(schemaName string) *NotifikasiTable {
	return newNotifikasiTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new NotifikasiTable with assigned table prefix
func (a NotifikasiTable) WithPrefix(prefix string) *NotifikasiTable {
	return newNotifikasiTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new NotifikasiTable with assigned table suffix
func (a NotifikasiTable) WithSuffix(suffix string) *NotifikasiTable {
	return newNotifikasiTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newNotifikasiTable(schemaName, tableName, alias string) *NotifikasiTable {
	return &NotifikasiTable{
		notifikasiTable: newNotifikasiTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newNotifikasiTableImpl("", "excluded", ""),
	}
}

func newNotifikasiTableImpl(schemaName, tableName, alias string) notifikasiTable {
	var (
		IDNotifikasiColumn   = postgres.IntegerColumn("id_notifikasi")
		IDUserColumn         = postgres.IntegerColumn("id_user")
		JudulColumn          = postgres.StringColumn("judul")
		PesanColumn          = postgres.StringColumn("pesan")
		TipeNotifikasiColumn = postgres.StringColumn("tipe_notifikasi")
		StatusBacaColumn     = postgres.BoolColumn("status_baca")
		TanggalKirimColumn   = postgres.TimestampzColumn("tanggal_kirim")
		IsDeletedColumn      = postgres.BoolColumn("is_deleted")
		DeletedAtColumn      = postgres.TimestampzColumn("deleted_at")
		allColumns           = postgres.ColumnList{IDNotifikasiColumn, IDUserColumn, JudulColumn, PesanColumn, TipeNotifikasiColumn, StatusBacaColumn, TanggalKirimColumn, IsDeletedColumn, DeletedAtColumn}
		mutableColumns       = postgres.ColumnList{IDUserColumn, JudulColumn, PesanColumn, TipeNotifikasiColumn, StatusBacaColumn, TanggalKirimColumn, IsDeletedColumn, DeletedAtColumn}
		defaultColumns       = postgres.ColumnList{IDNotifikasiColumn, StatusBacaColumn, TanggalKirimColumn, IsDeletedColumn}
	)

	return notifikasiTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDNotifikasi:   IDNotifikasiColumn,
		IDUser:         IDUserColumn,
		Judul:          JudulColumn,
		Pesan:          PesanColumn,
		TipeNotifikasi: TipeNotifikasiColumn,
		StatusBaca:     StatusBacaColumn,
		TanggalKirim:   TanggalKirimColumn,
		IsDeleted:      IsDeletedColumn,
		DeletedAt:      DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
