//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Pasien = newPasienTable("public", "pasien", "")

type pasienTable struct {
	postgres.Table

	// Columns
	IDPasien   postgres.ColumnInteger
	IDPosyandu postgres.ColumnInteger
	CreatedAt  postgres.ColumnTimestampz
	UpdatedAt  postgres.ColumnTimestampz
	IsDeleted  postgres.ColumnBool

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PasienTable struct {
	pasienTable

	EXCLUDED pasienTable
}

// AS creates new PasienTable with assigned alias
func (a PasienTable) AS(alias string) *PasienTable {
	return newPasienTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PasienTable with assigned schema name
func (a PasienTable) FromSchema(schemaName string) *PasienTable {
	return newPasienTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PasienTable with assigned table prefix
func (a PasienTable) WithPrefix(prefix string) *PasienTable {
	return newPasienTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PasienTable with assigned table suffix
func (a PasienTable) WithSuffix(suffix string) *PasienTable {
	return newPasienTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPasienTable(schemaName, tableName, alias string) *PasienTable {
	return &PasienTable{
		pasienTable: newPasienTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newPasienTableImpl("", "excluded", ""),
	}
}

func newPasienTableImpl(schemaName, tableName, alias string) pasienTable {
	var (
		IDPasienColumn   = postgres.IntegerColumn("id_pasien")
		IDPosyanduColumn = postgres.IntegerColumn("id_posyandu")
		CreatedAtColumn  = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn  = postgres.TimestampzColumn("updated_at")
		IsDeletedColumn  = postgres.BoolColumn("is_deleted")
		allColumns       = postgres.ColumnList{IDPasienColumn, IDPosyanduColumn, CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
		mutableColumns   = postgres.ColumnList{IDPosyanduColumn, CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
		defaultColumns   = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
	)

	return pasienTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDPasien:   IDPasienColumn,
		IDPosyandu: IDPosyanduColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,
		IsDeleted:  IsDeletedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
