//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Posyandu = newPosyanduTable("public", "posyandu", "")

type posyanduTable struct {
	postgres.Table

	// Columns
	IDPosyandu   postgres.ColumnInteger
	NamaPosyandu postgres.ColumnString
	IDLokasi     postgres.ColumnInteger
	IDBidan      postgres.ColumnInteger
	CreatedAt    postgres.ColumnTimestampz
	UpdatedAt    postgres.ColumnTimestampz
	IsDeleted    postgres.ColumnBool

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PosyanduTable struct {
	posyanduTable

	EXCLUDED posyanduTable
}

// AS creates new PosyanduTable with assigned alias
func (a PosyanduTable) AS(alias string) *PosyanduTable {
	return newPosyanduTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PosyanduTable with assigned schema name
func (a PosyanduTable) FromSchema(schemaName string) *PosyanduTable {
	return newPosyanduTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PosyanduTable with assigned table prefix
func (a PosyanduTable) WithPrefix(prefix string) *PosyanduTable {
	return newPosyanduTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PosyanduTable with assigned table suffix
func (a PosyanduTable) WithSuffix(suffix string) *PosyanduTable {
	return newPosyanduTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPosyanduTable(schemaName, tableName, alias string) *PosyanduTable {
	return &PosyanduTable{
		posyanduTable: newPosyanduTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newPosyanduTableImpl("", "excluded", ""),
	}
}

func newPosyanduTableImpl(schemaName, tableName, alias string) posyanduTable {
	var (
		IDPosyanduColumn   = postgres.IntegerColumn("id_posyandu")
		NamaPosyanduColumn = postgres.StringColumn("nama_posyandu")
		IDLokasiColumn     = postgres.IntegerColumn("id_lokasi")
		IDBidanColumn      = postgres.IntegerColumn("id_bidan")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampzColumn("updated_at")
		IsDeletedColumn    = postgres.BoolColumn("is_deleted")
		allColumns         = postgres.ColumnList{IDPosyanduColumn, NamaPosyanduColumn, IDLokasiColumn, IDBidanColumn, CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
		mutableColumns     = postgres.ColumnList{NamaPosyanduColumn, IDLokasiColumn, IDBidanColumn, CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
		defaultColumns     = postgres.ColumnList{IDPosyanduColumn, CreatedAtColumn, UpdatedAtColumn, IsDeletedColumn}
	)

	return posyanduTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDPosyandu:   IDPosyanduColumn,
		NamaPosyandu: NamaPosyanduColumn,
		IDLokasi:     IDLokasiColumn,
		IDBidan:      IDBidanColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,
		IsDeleted:    IsDeletedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
