//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Anak = Anak.FromSchema(schema)
	Artikel = Artikel.FromSchema(schema)
	AuditLog = AuditLog.FromSchema(schema)
	Bidan = Bidan.FromSchema(schema)
	DinasKesehatan = DinasKesehatan.FromSchema(schema)
	FasilitasKesehatan = FasilitasKesehatan.FromSchema(schema)
	GooseDbVersion = GooseDbVersion.FromSchema(schema)
	HasilPemeriksaan = HasilPemeriksaan.FromSchema(schema)
	IbuHamil = IbuHamil.FromSchema(schema)
	JadwalImunisasi = JadwalImunisasi.FromSchema(schema)
	KaderPosyandu = KaderPosyandu.FromSchema(schema)
	KategoriPendapatan = KategoriPendapatan.FromSchema(schema)
	Lokasi = Lokasi.FromSchema(schema)
	Notifikasi = Notifikasi.FromSchema(schema)
	Pasien = Pasien.FromSchema(schema)
	Pekerjaan = Pekerjaan.FromSchema(schema)
	Pendidikan = Pendidikan.FromSchema(schema)
	Posyandu = Posyandu.FromSchema(schema)
	Rujukan = Rujukan.FromSchema(schema)
	TindakLanjut = TindakLanjut.FromSchema(schema)
	UserAccount = UserAccount.FromSchema(schema)
	UserSession = UserSession.FromSchema(schema)
}
