//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserAccount = newUserAccountTable("public", "user_account", "")

type userAccountTable struct {
	postgres.Table

	// Columns
	IDUser           postgres.ColumnInteger
	Email            postgres.ColumnString
	Password         postgres.ColumnString
	NoHp             postgres.ColumnString
	StatusVerifikasi postgres.ColumnString
	Nama             postgres.ColumnString
	Nik              postgres.ColumnString
	JenisKelamin     postgres.ColumnString
	TanggalLahir     postgres.ColumnDate
	IDLokasi         postgres.ColumnInteger
	IDPendidikan     postgres.ColumnInteger
	IDPekerjaan      postgres.ColumnInteger
	IDPendapatan     postgres.ColumnInteger
	JumlahTanggungan postgres.ColumnInteger
	AkunKe           postgres.ColumnInteger
	CreatedAt        postgres.ColumnTimestampz
	UpdatedAt        postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserAccountTable struct {
	userAccountTable

	EXCLUDED userAccountTable
}

// AS creates new UserAccountTable with assigned alias
func (a UserAccountTable) AS(alias string) *UserAccountTable {
	return newUserAccountTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserAccountTable with assigned schema name
func (a UserAccountTable) FromSchema(schemaName string) *UserAccountTable {
	return newUserAccountTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserAccountTable with assigned table prefix
func (a UserAccountTable) WithPrefix(prefix string) *UserAccountTable {
	return newUserAccountTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserAccountTable with assigned table suffix
func (a UserAccountTable) WithSuffix(suffix string) *UserAccountTable {
	return newUserAccountTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserAccountTable(schemaName, tableName, alias string) *UserAccountTable {
	return &UserAccountTable{
		userAccountTable: newUserAccountTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newUserAccountTableImpl("", "excluded", ""),
	}
}

func newUserAccountTableImpl(schemaName, tableName, alias string) userAccountTable {
	var (
		IDUserColumn           = postgres.IntegerColumn("id_user")
		EmailColumn            = postgres.StringColumn("email")
		PasswordColumn         = postgres.StringColumn("password")
		NoHpColumn             = postgres.StringColumn("no_hp")
		StatusVerifikasiColumn = postgres.StringColumn("status_verifikasi")
		NamaColumn             = postgres.StringColumn("nama")
		NikColumn              = postgres.StringColumn("nik")
		JenisKelaminColumn     = postgres.StringColumn("jenis_kelamin")
		TanggalLahirColumn     = postgres.DateColumn("tanggal_lahir")
		IDLokasiColumn         = postgres.IntegerColumn("id_lokasi")
		IDPendidikanColumn     = postgres.IntegerColumn("id_pendidikan")
		IDPekerjaanColumn      = postgres.IntegerColumn("id_pekerjaan")
		IDPendapatanColumn     = postgres.IntegerColumn("id_pendapatan")
		JumlahTanggunganColumn = postgres.IntegerColumn("jumlah_tanggungan")
		AkunKeColumn           = postgres.IntegerColumn("akun_ke")
		CreatedAtColumn        = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn        = postgres.TimestampzColumn("updated_at")
		allColumns             = postgres.ColumnList{IDUserColumn, EmailColumn, PasswordColumn, NoHpColumn, StatusVerifikasiColumn, NamaColumn, NikColumn, JenisKelaminColumn, TanggalLahirColumn, IDLokasiColumn, IDPendidikanColumn, IDPekerjaanColumn, IDPendapatanColumn, JumlahTanggunganColumn, AkunKeColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns         = postgres.ColumnList{EmailColumn, PasswordColumn, NoHpColumn, StatusVerifikasiColumn, NamaColumn, NikColumn, JenisKelaminColumn, TanggalLahirColumn, IDLokasiColumn, IDPendidikanColumn, IDPekerjaanColumn, IDPendapatanColumn, JumlahTanggunganColumn, AkunKeColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns         = postgres.ColumnList{IDUserColumn, StatusVerifikasiColumn, AkunKeColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return userAccountTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDUser:           IDUserColumn,
		Email:            EmailColumn,
		Password:         PasswordColumn,
		NoHp:             NoHpColumn,
		StatusVerifikasi: StatusVerifikasiColumn,
		Nama:             NamaColumn,
		Nik:              NikColumn,
		JenisKelamin:     JenisKelaminColumn,
		TanggalLahir:     TanggalLahirColumn,
		IDLokasi:         IDLokasiColumn,
		IDPendidikan:     IDPendidikanColumn,
		IDPekerjaan:      IDPekerjaanColumn,
		IDPendapatan:     IDPendapatanColumn,
		JumlahTanggungan: JumlahTanggunganColumn,
		AkunKe:           AkunKeColumn,
		CreatedAt:        CreatedAtColumn,
		UpdatedAt:        UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
