//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserSession = newUserSessionTable("public", "user_session", "")

type userSessionTable struct {
	postgres.Table

	// Columns
	IDSession     postgres.ColumnString
	IDUser        postgres.ColumnInteger
	StatusSession postgres.ColumnString
	IPAddress     postgres.ColumnString
	ExpiredAt     postgres.ColumnTimestampz
	CreatedAt     postgres.ColumnTimestampz
	UpdatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserSessionTable struct {
	userSessionTable

	EXCLUDED userSessionTable
}

// AS creates new UserSessionTable with assigned alias
func (a UserSessionTable) AS(alias string) *UserSessionTable {
	return newUserSessionTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserSessionTable with assigned schema name
func (a UserSessionTable) FromSchema(schemaName string) *UserSessionTable {
	return newUserSessionTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserSessionTable with assigned table prefix
func (a UserSessionTable) WithPrefix(prefix string) *UserSessionTable {
	return newUserSessionTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserSessionTable with assigned table suffix
func (a UserSessionTable) WithSuffix(suffix string) *UserSessionTable {
	return newUserSessionTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserSessionTable(schemaName, tableName, alias string) *UserSessionTable {
	return &UserSessionTable{
		userSessionTable: newUserSessionTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newUserSessionTableImpl("", "excluded", ""),
	}
}

func newUserSessionTableImpl(schemaName, tableName, alias string) userSessionTable {
	var (
		IDSessionColumn     = postgres.StringColumn("id_session")
		IDUserColumn        = postgres.IntegerColumn("id_user")
		StatusSessionColumn = postgres.StringColumn("status_session")
		IPAddressColumn     = postgres.StringColumn("ip_address")
		ExpiredAtColumn     = postgres.TimestampzColumn("expired_at")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampzColumn("updated_at")
		allColumns          = postgres.ColumnList{IDSessionColumn, IDUserColumn, StatusSessionColumn, IPAddressColumn, ExpiredAtColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{IDUserColumn, StatusSessionColumn, IPAddressColumn, ExpiredAtColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{IDSessionColumn, StatusSessionColumn, ExpiredAtColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return userSessionTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IDSession:     IDSessionColumn,
		IDUser:        IDUserColumn,
		StatusSession: StatusSessionColumn,
		IPAddress:     IPAddressColumn,
		ExpiredAt:     ExpiredAtColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
